language: java
jdk:
- oraclejdk8
before_install:
  - git clone -b travis `git config --get remote.origin.url` target/travis
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml"

branches:
  only:
  - /^(?i:feature)/.*$/
  - develop
  - master

env:
  global:
  - secure: JOIhPH+x/NaWXvLTVNieMtNB+trIWgiM1ap2I42Z0I7+Rh4akpJF5ndbvayLWOKWfNBF0KdTfP1+OJu7LncG1WkgL9deUm15khlluwp9SRWd+T+jxAeIKdsImrZjTC47+RYvXI+9ltIvstjzcRrqDYYl0T2XXQP2p5Gyvt6gFA4vY3sLNfG7B48hqvIo/2Prvva7nDD0jyNQa03u98cpyJqJW69kBZcx4UhrjMAIkUX/yDhWbxcUxTgcrmyqVn66lQPye29Cs2WfDEthfF24lepx6tIZrqiCj2QElPGXDOvErjDG0I3ilJhtj0RTBQkKGta8IeV7pxXRC+3EB5NamZxXBHIP9C958QbU341Kuvi/ru6gD5vm5fhZI9gzo6Yf1ehr8KkihDfpLluK5BeyjTQGdat+9b4lTMOosZilE36J+dfx1BC8GSE/rYiBgGGxvtHwGNT6CYfXTbtJUCPbEmj81m2sYCAB9/FxPc6p7U+8qQw8BYndYcBymPthTFfgmZyohM/zZP7vjEM+63R4YneRGO7I4koKg0i7Z42NTqDyyWng2DcdOhaPuAYDZlGBPnThg1aUpm0v+q0veKQChIOEJ9tCYzTsVVE5aYm7D5+/4OHis/mszEs9AWbJYMa88p+yERXhm5jrx6JBTmoCKhxyUDpmn2nRg7V0aYadx44=
  - secure: tM84ivYSvS2qAwHhYJNjhoV2J8pRyHj+Eg6aZ1wIvRvxtMI08Ixk0tyN9cCQ9g2R5X/0OLIUBwmcLKnEF02o6t9eqq1MsQRzbITM+K2WvMKQnS0LN8Mc975djkeLj9+DpNwkyUOtr6nfX9Koes6OXB23c8pxJrnJN3O/0KGoqDzZgK4e4PpUmpGyFpcrHKnJ9EDZLdH6265B1muGr+P0FFFeWnZ6bU3pRYfOvQ0K7AwtiU0/IaxS8JU8kp/1OJUghyRBkcPfB03M7QMlW2mtVMsaHU6YEvMm7Y5igGfY0yiy/CrbRBUJPMuL2sKKb67HIgVHdF66jdhxZl+DYGAH8flD2uxgt8Kys/sn7I/ag/v9YcS9hKILcLq7SMXw1IFXoD+vddn4rEBZSJ46zR5guKlGr13qSSQV19Bw8C83Fx8ZLLLJJ0DZYq3unWlg9PFBxQCOHPB+pLPBOjuz9nNughsK4XmZkmPSuocJCHxZRMlhuuUFlIM2NdJEl5S1jef08l0iVWfuMsR7rjn+YmeNHJyoMEpJ5KHtwlZ9RDFGx50SDtqQ16hV01Bo66pWods+G3lm2AhiR8+8eTe+3YEAsHS/rBFHFr3UmAoptSjRpa6aSqVO8OuyXIlq8fG0ozP9vbMh1Pxet03RvdXVAYdjBg1Wc8XDbxeJ5t7JZVU9mEM=
