language: java
jdk:
  - oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script: mvn test -B
cache:
  directories:
    - ~/.m2/repository
branches:
  only:
    - "/^(?i:feature)/.*$/"
    - develop
    - master
after_success:
# FIXME: not able to repo-token not working
#  - mvn clean test -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID jacoco:report cobertura:cobertura coveralls:report
  - mvn clean test jacoco:report cobertura:cobertura coveralls:report
  - "./.travis/before-deploy.sh"
  - "./.travis/deploy.sh"
env:
  global:
    - secure: cVN7kR9iipOTSZi1RK4oouBpV5m9fzefzkikRjXOxh2ihCZhU2dIFtdoFUoPPQIm/Zjau7BtotucgnLKWiYpB+9yQciJ53hjqQx0uPZydTt2LckfMgtvg6Mjbj8MQeK5y6SssxQGcitU+xORPZfhYR4nUgnCEkQIFHyWpU4y2mh30y5CIxfPJDw/0/9N6tdQxJjw+13N9cfFj7JwXoiR1+x1/NY7KZ018MtaKnFD9+Zv5lHAqwbqFRTL69hbVkg7riDPiYEJl+R2Dab8HGt6xxCOu6Mm97INnkz+u//ftbLZwdg7a2USZKGCLtAcaKnF7QSc2Yo3d+x4b7DCKmqcDqX3Szq+SLrq2JCNu7Q93Msj9zmZKd7BQby6Zjw43GZRifjwDeUPT498v0ZQkBhpt3mfFAimAM8ZPeX4wlj45cB8uePhBQ2Tifk8IXY/hEldnJ1/OQYZKUMglHAyCN9l4UsXkhCjdT2RbbN4yJZec8zS//KA+SGbz2DGLVVTVbCwZiEO3TT32Sy2vpawKPZ8HScmmzMoJaYvBYYjK2f7pcanDxvIufLnZekRfHS0BUNTdNrianASVPU68gTfR3W2WDv2+m6Vrh6Q+yjz1LjjkAStpuDWOfrJmWFXWKQzTLCEJPDWyo8HHxtCJRdQ9Icr6GrHzBYyrMBHrJA/WVbtl68=
    - secure: Cc5IXxQ2oQicHykAbmVRGoGCcZRGlgANqNbz+iaE19PkZyhkZ6f6J253QNiS64g3iniNRVouhH04kERgk2IxuW/+FckSCNJlUktoWS+M6/FS/HG2yCTOxiNQRGPRYI3SKl9b7cftsRzlA6GiIxUvd5n4nryGqQZPwIEix7AXFdWX3zHzaYUP+mcdHbrKMqBgXn3AfJhYtn6KH47tkUHcw2fSJpZo3xaL1gkH3NKsW8Y2odSuM8Bsx4VOfl2Rbp/hY0y/O0fkWD5mru4vcWUXWWrZVy5Fc3D1oPlPacFKlBBvpaSGkDk8dfpaUYqqmEpmFBrapcBjmHEagrEfZ8SMfQum+9xvW2gglCiC+WSlR+0T4SaOQW25HvwFNtr4bGvIoiUjXoCmiRv2wv5+gSZgLQmqxzCxM/HEP9G3+U9onv6QVUp7icx7vscAYjzU6HNNIR5XFbQCSxF1XRm18+AkPtAmUUoXfY4yUb5UjlRwN+Opv58o/Cw64o8/svEgY7oQcvpoTl9U9XLfGuTc+9GFh8fjGWVdVP+nY3JV9A58NniUMjJ3GfA2rdKA3B/XDjhLZljnuVv1wvGM69PBu74n2FwfMLONs7PsD69ws0kitg0+iS12iXb4ygVhtIQg9jJ0uQBRfOtQScbTP50XuuAfNZ1vfHykAGCq94x9RBDV8Ps=
    - secure: ZypWaCmbA9e+ZDhTa4Gd1ooAEOFSZ6KzmIfq1pa8wT2AfNpPGigxehvGNRZI+6Ecvt9P0FLiM+qkGxTm0U84NCkZHf/g/9z+X+KA0K0doV+2Hzc0uUQYYIvgPZz5XEwF5BNUo/mTdV6XpItrEZvuPGxPpOVQf4s/0exyGcOIXKdV07mVKulRu5PntsRHnfMoqILiyGikh3ixL6zs+Boy+RIq+5iu+Y0mCAXEN4QalPAbqso+6ovUgCgfDx3o+DgL7DRxbAFYm8NgbthSbhQx+Q72JcqshxiDbLse91SeDUnhxtuWgzdFpKh2hvmfcvB1XmX8YcO8S0G16yLQ/bTvVBcP29I9Xu1Q3UkmFoEwNiXmymV30bp1gZAyZN85B+ATVafLmSYQfxO39AKfBFS8Zh05PakVOtkZNNTNDGvuWsXtLarK6xXV4FX+Pg2IUbrWf9CLuVrX6G+aCBE4mnZYIJiAGaWbimoa2D8pf3vaHYzmP4h/v7FJU2NEW35fM7cOG6+BnipSNm3M2TnfoQp6Y+3JU/Qg5nW+t7XyhC1P72aToracWWzNe/YVI4qaSVg3jYUyHCkwfQVBifaqkxtcia1aCCyfx/c7g8aoyy5hpftvXA7e/yUrfdpy4Siudi8OcU0w6LaUwYhfxBF8fOPsyL9IinUstD/ylsz6T0onXGI=
    - secure: dp7Tf+O2xy5cSSOpa0m8e9IBffdJmowooPL8dQ5B9zSvhA3PIp2H80AlMjKcloMSr9ED0nXuZUkrOIfuP+UBLCZ36/CrOqjDdVKe5RPXlTtqgF28pztnuKoLNOS9Y+FirjuCe+SPu+J0lu7xsfHcXUUR1iTRg5FLtc8mNUrbpkpDbi6xWGmzDBgVd9MFwyhOzwwsP4bk5CPUzwliZ2dyStcRNtLcSRQZx3JClaTWg19ueKpoca1eEncZ6jXhYzI15zVty5ZYzNNl8OXtjbCihNj60Ij2nA6H3+GvDoaJczH+3ekRtkK5bfzHf022AXugYEVqzGsaL+T9lDLyu2+bV291N4VE/ym8g1EJeAQYO45GkyayJ6uxu+9Leo4gXpLsC/h+T4GpB5BVuWEzsuIX+KQX1E7BbI6MPvRf6Kkbwhq3omN2A5GEw3zdHHjvY5r058JsZAi3K5ZPJXONK3utVBQDtHwU5zg1wGp7ggegwF7GLt1lnmSXAhDUibTxeaCFDrexXyc30vB89tfe7uFnlzyVUYwBo4/VIO4QhwcxPaPD1lkxuJV1epkoYoTj1VYmrKnGeiYJS6toEkgI77dtse5RrAVmrFpZsXouXIqegwUfJ58HR7ENhC5yT00aUJBjyUm8R5E3Uj08AeWKxiWjB85JiqHTApTCijo0dQqo47c=
notifications:
  email:
    - james.w.todd@gmail.com
