language: java
jdk:
  - oraclejdk8

install:
  - mvn --settings settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -x

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  - mvn clean deploy --settings settings.xml -DskipTests=true -B -U -x
branches:
  only:
  - /^(?i:feature)/.*$/
  - develop
  - master